version: '3.7'

volumes:
  db: 

networks:
  mattermost:

services:
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - mattermost
    ports: 
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: really_secure_password
      POSTGRES_DB: mattermost

  ldap:
    container_name: ldap
    image: osixia/openldap
    ports:
      - 389:389
    command: [--copy-service,  --loglevel, debug]
    volumes:
      - /tmp/ldifs:/container/service/slapd/assets/config/bootstrap/ldif/custom
    environment:
      LDAP_BASE_DN: dc=planetexpress,dc=com
      LDAP_ORGANISATION: Planet Express, Inc.
      LDAP_DOMAIN: planetexpress.com
      LDAP_ADMIN_PASSWORD: GoodNewsEveryone
    networks:
      - mattermost

  ldapadmin:
    container_name: ldapadmin
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
        PHPLDAPADMIN_LDAP_HOSTS: "ldap"
        PHPLDAPADMIN_HTTPS: "false"
    networks:
      - mattermost
    ports:
        - 5000:80
    depends_on:
        - ldap

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 10025:1025
      - 8025:8025